# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: indy7_arm
  joint_model_group_pose: zero
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint0
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - rh_l1
    - rh_l2
    - rh_p12_rn_a
    - rh_r2
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: indy7_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
  - name: indy7_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
    - rh_l1
    - rh_l2
    - rh_p12_rn_a
    - rh_r2
indy7_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint0
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
  gains:
    joint0:
      p: 10000
      d: 1
      i: 1
      i_clamp: 1
    joint1:
      p: 10000
      d: 1
      i: 1
      i_clamp: 1
    joint2:
      p: 10000
      d: 1
      i: 1
      i_clamp: 1
    joint3:
      p: 10000
      d: 1
      i: 1
      i_clamp: 1
    joint4:
      p: 10000
      d: 1
      i: 1
      i_clamp: 1
    joint5:
      p: 10000
      d: 1
      i: 1
      i_clamp: 1
indy7_hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - rh_l1
    - rh_l2
    - rh_p12_rn_a
    - rh_r2
  gains:
    rh_l1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rh_l2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rh_p12_rn_a:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rh_r2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
